# Generated by Django 4.2 on 2026-02-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loanapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='proof_of_income',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='valid_id',
        ),
    ]
