# Generated by Django 4.2 on 2026-02-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_loanapplication_proof_of_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='term',
            field=models.IntegerField(default=12),
        ),
    ]
